server:
  host: "127.0.0.1"
  port: 3000

chains:
  ethereum:
    name: "Ethereum Mainnet"
    protocol: "jsonrpc"
    base_url: "https://ethereum-rpc.publicnode.com"

  solana:
    name: "Solana Mainnet"
    protocol: "jsonrpc"
    base_url: "https://api.mainnet-beta.solana.com"

  sui:
    name: "Sui Mainnet"
    protocol: "jsonrpc"
    base_url: "https://fullnode.mainnet.sui.io:443"
