[server]
host = "127.0.0.1"
port = 3000

[chains.ethereum]
name = "Ethereum"
protocol = "jsonrpc"

[chains.ethereum.mainnet]
name = "Ethereum Mainnet"
rpc_url = "https://ethereum-rpc.publicnode.com"

[chains.ethereum.testnets.sepolia]
name = "Ethereum Sepolia"
rpc_url = "https://ethereum-sepolia-rpc.publicnode.com"

[chains.solana]
name = "Solana"
protocol = "jsonrpc"

[chains.solana.mainnet]
name = "Solana Mainnet"
rpc_url = "https://api.mainnet-beta.solana.com"

[chains.solana.testnets.devnet]
name = "Solana Devnet"
rpc_url = "https://api.devnet.solana.com"

[chains.sui]
name = "Sui"
protocol = "jsonrpc"

[chains.sui.mainnet]
name = "Sui Mainnet"
rpc_url = "https://fullnode.mainnet.sui.io:443"

[chains.sui.testnets.testnet]
name = "Sui Testnet"
rpc_url = "https://fullnode.testnet.sui.io:443"
